---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-deployment
  labels:
    app: ecomm-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: veerareddy1422/ecomm
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    tier: frontend
